#!/bin/csh
#PBS -l select=13:ncpus=20:model=ivy
#PBS -l walltime=2:00:00
#PBS -q devel
#PBS -j oe
#PBS -m abe

module purge
module load comp-intel/2020.4.304
module load mpi-hpe/mpt
module load hdf4/4.2.12 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt
module list

cd $PBS_O_WORKDIR
limit stacksize unlimited
mpiexec -np 256 ./mitgcmuv
